// <auto-generated />
using FootballClubApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballClubApp.Migrations
{
    [DbContext(typeof(FootballClubAppDbContext))]
    [Migration("20220130195041_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FootballClubApp.Entities.Opponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Competition")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Opponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Competition = 1,
                            TeamName = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            Competition = 1,
                            TeamName = "Atletico Madrid"
                        },
                        new
                        {
                            Id = 3,
                            Competition = 3,
                            TeamName = "SSC Napoli"
                        });
                });

            modelBuilder.Entity("FootballClubApp.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ansu",
                            IsCaptain = false,
                            LastName = "Fati",
                            Number = "10",
                            Position = 4
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Gerard",
                            IsCaptain = false,
                            LastName = "Piqué",
                            Number = "3",
                            Position = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Marc-André",
                            IsCaptain = false,
                            LastName = "ter Stegen",
                            Number = "1",
                            Position = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Pablo",
                            IsCaptain = false,
                            LastName = "Gavi",
                            Number = "30",
                            Position = 3
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Sergio",
                            IsCaptain = true,
                            LastName = "Busquets",
                            Number = "5",
                            Position = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
